// Code generated by github.com/infiotinc/genqlient, DO NOT EDIT.

package main

import (
	"context"
	"time"

	"github.com/aarondl/json"
	"github.com/infiotinc/genqlient/graphql"
)

// __getUserInput is used internally by genqlient
type __getUserInput struct {
	Login string `json:"Login"`
}

// GetLogin returns __getUserInput.Login, and is useful for accessing the field via an interface.
func (v *__getUserInput) GetLogin() string { return v.Login }
func (v __getUserInput) MarshalJSON() ([]byte, error) {
	type ___getUserInput __getUserInput
	vv := ___getUserInput(v)
	return json.Marshal(vv)
}

func (v *__getUserInput) UnmarshalJSON(b []byte) error {
	type ___getUserInput __getUserInput
	var vd ___getUserInput
	err := json.Unmarshal(b, &vd)
	if err != nil {
		return err
	}
	*v = __getUserInput(vd)
	return nil
}

// getUserResponse is returned by getUser on success.
type getUserResponse struct {
	// Lookup a user by login.
	User getUserUser `json:"user"`
}

// GetUser returns getUserResponse.User, and is useful for accessing the field via an interface.
func (v *getUserResponse) GetUser() getUserUser { return v.User }
func (v getUserResponse) MarshalJSON() ([]byte, error) {
	type _getUserResponse getUserResponse
	vv := _getUserResponse(v)
	return json.Marshal(vv)
}

func (v *getUserResponse) UnmarshalJSON(b []byte) error {
	type _getUserResponse getUserResponse
	var vd _getUserResponse
	err := json.Unmarshal(b, &vd)
	if err != nil {
		return err
	}
	*v = getUserResponse(vd)
	return nil
}

// getUserUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type getUserUser struct {
	// The user's public profile name.
	TheirName string `json:"theirName"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetTheirName returns getUserUser.TheirName, and is useful for accessing the field via an interface.
func (v *getUserUser) GetTheirName() string { return v.TheirName }

// GetCreatedAt returns getUserUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *getUserUser) GetCreatedAt() time.Time { return v.CreatedAt }
func (v getUserUser) MarshalJSON() ([]byte, error) {
	type _getUserUser getUserUser
	vv := _getUserUser(v)
	return json.Marshal(vv)
}

func (v *getUserUser) UnmarshalJSON(b []byte) error {
	type _getUserUser getUserUser
	var vd _getUserUser
	err := json.Unmarshal(b, &vd)
	if err != nil {
		return err
	}
	*v = getUserUser(vd)
	return nil
}

// getViewerResponse is returned by getViewer on success.
type getViewerResponse struct {
	// The currently authenticated user.
	Viewer getViewerViewerUser `json:"viewer"`
}

// GetViewer returns getViewerResponse.Viewer, and is useful for accessing the field via an interface.
func (v *getViewerResponse) GetViewer() getViewerViewerUser { return v.Viewer }
func (v getViewerResponse) MarshalJSON() ([]byte, error) {
	type _getViewerResponse getViewerResponse
	vv := _getViewerResponse(v)
	return json.Marshal(vv)
}

func (v *getViewerResponse) UnmarshalJSON(b []byte) error {
	type _getViewerResponse getViewerResponse
	var vd _getViewerResponse
	err := json.Unmarshal(b, &vd)
	if err != nil {
		return err
	}
	*v = getViewerResponse(vd)
	return nil
}

// getViewerViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type getViewerViewerUser struct {
	// The user's public profile name.
	MyName string `json:"MyName"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetMyName returns getViewerViewerUser.MyName, and is useful for accessing the field via an interface.
func (v *getViewerViewerUser) GetMyName() string { return v.MyName }

// GetCreatedAt returns getViewerViewerUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *getViewerViewerUser) GetCreatedAt() time.Time { return v.CreatedAt }
func (v getViewerViewerUser) MarshalJSON() ([]byte, error) {
	type _getViewerViewerUser getViewerViewerUser
	vv := _getViewerViewerUser(v)
	return json.Marshal(vv)
}

func (v *getViewerViewerUser) UnmarshalJSON(b []byte) error {
	type _getViewerViewerUser getViewerViewerUser
	var vd _getViewerViewerUser
	err := json.Unmarshal(b, &vd)
	if err != nil {
		return err
	}
	*v = getViewerViewerUser(vd)
	return nil
}

// The query or mutation executed by getUser.
const getUser_Operation = `
query getUser ($Login: String!) {
	user(login: $Login) {
		theirName: name
		createdAt
	}
}
`

// getUser gets the given user's name from their username.
func getUser(
	ctx_ context.Context,
	client_ graphql.Client,
	Login string,
) (*getUserResponse, error) {
	req_ := &graphql.Request{
		OpName: "getUser",
		Query:  getUser_Operation,
		Variables: &__getUserInput{
			Login: Login,
		},
	}
	var err_ error

	var data_ getUserResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by getViewer.
const getViewer_Operation = `
query getViewer {
	viewer {
		MyName: name
		createdAt
	}
}
`

func getViewer(
	ctx_ context.Context,
	client_ graphql.Client,
) (*getViewerResponse, error) {
	req_ := &graphql.Request{
		OpName: "getViewer",
		Query:  getViewer_Operation,
	}
	var err_ error

	var data_ getViewerResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
